name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3

    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.settings.target }}
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose

  cross:
    
    strategy:
      matrix:
        settings:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: macos-latest
            target: aarch64-apple-darwin
          - host: windows-latest
            target: x86_64-pc-windows-msvc
    
    runs-on: ${{ matrix.settings.host }}

    steps:
    
    - uses: actions/checkout@v3

    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.settings.target }}
    
    - run: rustup target add ${{ matrix.settings.target }}
    - run: cargo build --release --target ${{ matrix.settings.target }}
    - run: find target -type f

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.settings.target }}
        path: target/${{ matrix.settings.target }}/release/sso-profiles
        retention-days: 7